### ISSUE TITLE
waybar图标设置

### ISSUE THREAD

**Issue by imethwang** [ch3n9w/MyDots#1]
我已经安装了otf-font-awesome，但还是无法在vim里编辑waybar配置文件中的icon

**Comment by ch4xer** [comment]
安装一下Nerd Font的字体, 如果[这个文件中的字符集](https://github.com/syvanpera/dotfiles-yadm/blob/1e27ddcc26750915b0d007f2f2a360b76e1b2677/scripts/nerd-chars.csv)都可以显示就没有问题了,

**Comment by imethwang** [comment]
多谢
